# BUILD: docker build --no-cache --rm -t temp/solution:3-builder -f Dockerfile-builder .
# RUN:   docker run --rm temp/solution:3-builder

FROM golang:1-alpine

# Mount Project and output volumes
VOLUME $GOPATH/src/github.com/JulienBreux/go-program-in-docker
VOLUME /output

# Change workdir to project path
WORKDIR $GOPATH/src/github.com/JulienBreux/go-program-in-docker

# Create application to put to the new image
CMD GOOS=linux GOARCH=amd64 go build -o /output/app
